// Precompiles the Milkdrop presets' equations into real functions (run from app/ after changing butterchurn-presets):
//
//   node src/renderer/src/visuals/engines/milkdrop/gen-eqs.mjs
//
// Butterchurn turns each preset's equation strings into code with `new Function`, which the renderer's CSP rightly
// forbids (script-src 'self', no 'unsafe-eval'). It skips that when a preset already carries functions, so this
// writes them out as a module: same bodies, same `a` argument, `return a` appended, as butterchurn builds them.
// Module code is strict: every equation of the pack was checked to run the same strict and sloppy.
import { writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const presets = require('butterchurn-presets').getPresets()
const { version } = require('butterchurn-presets/package.json')

const fn = (body) => `function (a) {\n${body || ''}\nreturn a;\n}`
// pixel and point equations: '' when empty, as butterchurn marks "none" (it only runs them when present)
const optional = (body) => (body ? fn(body) : "''")
const entries = Object.entries(presets).map(([name, p]) => {
  const shapes = p.shapes.map((s) => `[${fn(s.init_eqs_str)}, ${fn(s.frame_eqs_str)}]`)
  const waves = p.waves.map((w) => `[${fn(w.init_eqs_str)}, ${fn(w.frame_eqs_str)}, ${optional(w.point_eqs_str)}]`)
  return `${JSON.stringify(name)}: {\ni: ${fn(p.init_eqs_str)},\nf: ${fn(p.frame_eqs_str)},\np: ${optional(p.pixel_eqs_str)},\ns: [${shapes.join(',\n')}],\nw: [${waves.join(',\n')}]\n}`
})
const out = new URL('./eqs.gen.js', import.meta.url)
writeFileSync(out, `// Generated by gen-eqs.mjs from butterchurn-presets ${version} (MIT). Do not edit.\n/* eslint-disable */\nexport default {\n${entries.join(',\n')}\n}\n`)
console.log(`wrote ${Object.keys(presets).length} presets' equations to ${out.pathname}`)
